### ISSUE TITLE
Создать страницу профиля User

### ISSUE THREAD

**Issue by nakermaz** [DJ-Java-Team/youmiteru-backend#24]
`# НА ДОРАБОТКЕ
`
Нужно написать ответ для страницы User 

```json
{
"userId": 1,
"profile_picture_url": "url_image",
"name": "RainGor"
}

```

![Image](https://github.com/DJ-Java-Team/youmiteru-backend/assets/109914187/836a3448-1a8a-42db-a4db-8418d72b22d1)

**Comment by RaingGOR** [comment]
Добавим еще Favorite

**Comment by RaingGOR** [comment]
## Страница должна включать: 
- [ ] Айди юзера
- [ ] Профильную картинку
- [ ] Ник
- [ ] Лист с любимыми аниме
