### ISSUE TITLE
Изменение дто на нормальные

### ISSUE THREAD

**Issue by RaingGOR** [DJ-Java-Team/youmiteru-backend#30]
Изучаем что такое рекорды и переходим на них

**Comment by nakermaz** [comment]
добавь побольше информации, а то ничего не понятно 

![Image](https://github.com/DJ-Java-Team/youmiteru-backend/assets/109914187/320380e2-4404-4965-ac1f-526ebd6f439d)

**Comment by RaingGOR** [comment]
Че понятнее то, use record how DTO

**Comment by RaingGOR** [comment]
Это шкипа будет задание, ну его тебе в руки отдавать рефакторинг всего кода

**Comment by RaingGOR** [comment]
![QqgJWEez-ME.jpg](https://github.com/DJ-Java-Team/youmiteru-backend/assets/120410372/bdff2b80-3693-4483-850b-76e508df7c65)

**Comment by nakermaz** [comment]
ну тогда я заберу создания профиля)
