### ISSUE TITLE
Админ панель

### ISSUE THREAD

**Issue by RaingGOR** [DJ-Java-Team/youmiteru-backend#41]

**Comment by InalGagiev** [comment]
- [ ] crud к сезонам
- [ ] crud к тайтлам
- [ ] crud к жанрам, а так же связ жанров и аниме
- [ ] crud к актерам озвучки, их связь с сезонами
- [ ] crud к видео
- [ ] crud к комментам(удалять)
- [ ] crud к тайтлу

**Comment by nakermaz** [comment]
![Image](https://github.com/DJ-Java-Team/youmiteru-backend/assets/109914187/ecb796b6-e96a-4b14-9daa-25cbfaef5f7f)
