### ISSUE TITLE
Название задачи: Добавление поддержки OAuth2 для аутентификации через Discord, ВКонтакте и Google в Spring проекте

### ISSUE THREAD

**Issue by RaingGOR** [DJ-Java-Team/youmiteru-backend#46]
**Описание задачи:**
Необходимо реализовать механизм аутентификации пользователей через OAuth2 с использованием Discord, ВКонтакте и Google в аниме проекте. Это позволит пользователям использовать свои учетные записи из этих платформ для входа на сайт.

**Шаги**:
1. Настройка клиентских приложений OAuth2:
   - Зарегистрировать приложения на платформах Discord, ВКонтакте и Google для получения клиентских идентификаторов и секретных ключей.
   - Указать разрешенные URI перенаправления для успешной аутентификации.

2. Интеграция Spring Security OAuth2:
   - Добавить зависимости Spring Security OAuth2 и необходимые клиентские библиотеки в файл `pom.xml` (для Maven) или `build.gradle` (для Gradle).
   - Создать конфигурационный класс для Spring Security OAuth2.

3. Настройка провайдеров авторизации:
   - Настроить провайдеров авторизации для каждой платформы (Discord, ВКонтакте, Google), указав клиентские идентификаторы и секретные ключи.
   - Определить URI авторизации и URI обратного вызова для каждого провайдера.

4. Реализация контроллеров и сервисов:
   - Создать контроллеры и сервисы для обработки успешной аутентификации и получения информации о пользователе от провайдеров.
   - Реализовать логику создания учетной записи пользователя на основе полученных данных от провайдеров.

5. Тестирование:
   - Провести тестирование функционала аутентификации через Discord, ВКонтакте и Google, убедившись, что пользователи успешно могут войти на сайт с использованием своих аккаунтов.

8. Интеграция существующего функционала:
   - Интегрировать механизм OAuth2 с существующими контроллерами и сервисами, учитывая требования безопасности и функциональности проекта.

Важно также обеспечить безопасность при обработке данных пользователей и соблюдение политики конфиденциальности при использовании механизма OAuth2.

**Comment by nakermaz** [comment]
![Image](https://github.com/DJ-Java-Team/youmiteru-backend/assets/109914187/b5798acd-865c-47c6-a0c9-51620abced4c)
